# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux
  - osx
  - windows

julia:
  - 1.0
  - 1
  - nightly

branches:
  only:
  - master

notifications:
  email: false

jobs:
  allow_failures:
    - julia: nightly
  include:
    - stage: "Documentation"
      julia: 1
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
